"""Add editing_sessions table

Revision ID: 145dd6f4cdc6
Revises: 053f9bbdc6f0
Create Date: 2025-08-24 06:49:59.197354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145dd6f4cdc6'
down_revision = '053f9bbdc6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editing_sessions')
    # ### end Alembic commands ###
