"""Add default_tasks table

Revision ID: 703ab58d328e
Revises: bdbba856f814
Create Date: 2025-08-24 11:05:53.603997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ab58d328e'
down_revision = 'bdbba856f814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounting_method', sa.String(length=255), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accounting_method')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_tasks')
    # ### end Alembic commands ###
