"""Add is_inactive field to Client model

Revision ID: 8d7c67a89933
Revises: 145dd6f4cdc6
Create Date: 2025-08-24 16:37:43.743960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7c67a89933'
down_revision = '145dd6f4cdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        # First add column with default value and nullable=True
        batch_op.add_column(sa.Column('is_inactive', sa.Boolean(), nullable=True, server_default='false'))
    
    # Update all existing records to have is_inactive=False
    op.execute("UPDATE clients SET is_inactive = FALSE WHERE is_inactive IS NULL")
    
    # Now make it NOT NULL
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('is_inactive', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_inactive')

    # ### end Alembic commands ###
